name: lorenzoconti
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  url_launcher: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets\portfolio.jpg

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts\Raleway-Bold.ttf
          weight: 700
        - asset: fonts\Raleway-Italic.ttf
          style: italic
        - asset: fonts\Raleway-Light.ttf
        - asset: fonts\Raleway-Regular.ttf